name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        cd docs
        pip install -r requirements.txt
    - name: Build HTML
      run: |
        cd docs
        make html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.SPHINX_GITHUB_TOKEN }}
        publish_dir: docs/_build/html
